export const CONFIG = {
    title: "TechNo Store",
    slogan: "Công nghệ đích thực - Giá trị bền vững",
    description: "Chuyên cung cấp điện thoại chính hãng & phụ kiện gaming chính hãng",

    salesTitle: "Ưu đãi tháng 7",
    salesOff: 50,

    address: "1125 Nguyễn Bình, Xã Hiệp Phước, TP. Hồ Chí Minh",
    hotline: "0123 456 789",
    email: "technostore@gmail.com",
};

export const DETAIL = {
    iPhone15ProMax: {
        name: "iPhone 15 Pro Max",
        cost: 39990000,
        color: { black: "Đen", white: "Trắng", titan: "Titan" },
        memory: { small: "256GB", medium: "512GB", large: "1TB" },
        details: {
            OS: "iOS",
            screenSize: "6.7 inches",
            screenDetail: "Tốc độ làm mới 120Hz | 460 ppi | 2000 nits | HDR | True Tone | Dải màu rộng (P3) | Haptic Touch | Tỷ lệ tương phản 2.000.000:1",
            chip: "Apple A17 Pro 6 nhân",
            ram: "8GB",
            rearCamera: "Camera chính: 48MP, 24 mm, ƒ/1.78 | Camera góc siêu rộng: 12MP, 13 mm, ƒ/2.2 | Camera Tele: 12MP",
            frontCamera: "Camera trước: 12MP, ƒ/1.9",
            battery: "4422 mAh",
        },
    },
    SamsungS24Ultra: {
        name: "Samsung Galaxy S24 Ultra",
        cost: 31990000,
        color: { black: "Đen", white: "Trắng", blue: "Xanh", pink: "Hồng" },
        memory: { small: "256GB", medium: "512GB", large: "1TB" },
        details: {
            OS: "Android 14, One UI 6.1",
            screenSize: "6.8 inches",
            screenFeature: "Dynamic AMOLED 2X | 120Hz | Độ sáng tối đa 2.600 nits | HDR10+ | Độ phân giải 1440x3120 pixels",
            chip: "Snapdragon 8 Gen 3",
            ram: "12GB",
            rearCamera: "Camera chính: 200MP, Laser AF, OIS | Camera tele: 50MP, PDAF, OIS, zoom quang học 5x | Camera tele: 10MP | Camera góc siêu rộng: 12MP, f/2.2, 13mm, 120°",
            frontCamera: "Camera trước: 12MP, f/2.2",
            battery: "5.500 mAh",
        },
    },
    Xiaomi14Pro: {
        name: "Xiaomi 14 Pro",
        cost: 21990000,
        color: { black: "Đen", grey: "Xám", purple: "Tím", gold: "Vàng" },
        memory: { small: "256GB", medium: "512GB", large: "1TB" },
        details: {
            OS: "Android 14, HyperOS",
            screenSize: "6.73 inches",
            screenFeature: "LTPO AMOLED | 68 tỷ màu | 120Hz | Dolby Vision | HDR10+ | Độ sáng tối đa 3000 nits",
            chip: "Snapdragon 8 Gen 3",
            ram: "12GB",
            rearCamera: "Camera chính: 50MP, f/1.4–f/4.0, OIS | Camera tele: 50MP, zoom quang 3.2x, OIS | Camera góc siêu rộng: 50MP",
            frontCamera: "Camera trước: 32MP, f/2.2",
            battery: "4.880 mAh",
        },
    },
    OppoFindX7Ultra: {
        name: "OPPO Find X7 Ultra",
        cost: 25299000,
        color: { black: "Đen", green: "Xanh", brown: "Nâu" },
        memory: { small: "256GB", medium: "512GB", large: "1TB" },
        details: {
            OS: "Android 14, ColorOS",
            screenSize: "6.82 inches",
            screenFeature: "LTPO AMOLED | 68 tỷ màu | 120Hz | Dolby Vision | HDR10+ | Độ sáng tối đa 4500 nits | Độ phân giải QHD+ (1440x3168)",
            chip: "Snapdragon 8 Gen 3",
            ram: "12GB - 16GB",
            rearCamera: "Camera chính: 50MP, f/1.4–f/4.0, OIS | Camera tele: 50MP, zoom quang 3.2x, OIS | Camera góc siêu rộng: 50MP | Camera tele tiềm vọng: 50MP, zoom quang 6x, OIS",
            frontCamera: "Camera trước: 32MP",
            battery: "5.000 mAh",
        },
    },
    gamingKeyboard: {
        name: "Bàn Phím Gaming HyperX",
        cost: 750000,
        model: "HX-KB1SS2-US",
        light: "RGB",
        keyswitch: "Kailh Silver Speed",
        keyCount: "104 phím",
        pollingRate: "1000Hz",
        connect: "USB 2.0",
        keyRollover: "N-Key, 100% Anti-Ghosting",
        cable: "Dây cáp 1.8m, dây bện tháo rời",
        switchDurability: "70 triệu lượt nhấn",
        compatibility: "PC, PS5, PS4, Xbox Series X|S, Xbox One",
        brand: "HyperX",
    },
    gamingMouse: {
        name: "Chuột Logitech G304",
        cost: 580000,
        compatibility: "PC, Xbox Series X|S, Xbox One, PS5, PS4",
        resolution: "400 / 800 / 1600 / 3200 / 26000 DPI",
        connect: "2.4GHz Wireless / Bluetooth 5.1 / Có dây",
        distanceConnect: "10m",
        battery: "100 giờ",
        brand: "Logitech",
    },
    gamingHeadphone: {
        name: "Tai Nghe HyperX",
        cost: 800000,
        audiotechnology: "Âm thanh 3D",
        feature: "Có micro",
        connect: "3.5mm",
        brand: "HyperX",
    },
    gamingMouseG102: {
        name: "Chuột Logitech G102",
        cost: 700000,
        model: "G102 Lightsync",
        compatibility: "PC, PS5, PS4, Xbox Series X|S, Xbox One",
        resolution: "200 / 800 / 1600 / 3200 / 8000 DPI",
        connect: "USB 2.0",
        cable: "2.1m",
        feature: "RGB Lightsync, 6 nút lập trình",
        weight: "85g",
        brand: "Logitech",
    },
};
